import Head from "next/head";
import Navigation from "@/components/Navigation";
import ProductFeed from "@/components/ProductFeed";
import Header from "@/components/Header";

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* NavBar */}
      <Header />
      <main className="flex flex-col md:flex-row">
        <Navigation />
        <ProductFeed products={products} />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const req = await fetch("https://dummyjson.com/products/category/groceries");
  const res = await req.json();
  const products = res.products;

  return {
    props: { products },
  };
}
